### ISSUE TITLE
moving spritipy.py in the root directory

### ISSUE THREAD

**Issue by pbellec** [brainsprite/brainsprite.py#3]
seems to be consistent with http://docs.python-guide.org/en/latest/writing/structure/

I find accessing ~/git/spritipy/spritipy/spytipy.py ridiculously awkward.
  Let's get rid of at least one level of the hierarchy.

**Comment by pbellec** [comment]
And, while I am at it, brainsprite.py would make much more sense. spritipy sounds like THE library to make sprites in python. It's not. Also, spritipy will have api to generate stand-alone brainsprite viz, or inject them into a notebook. This is inconsistent with the name spritipy, but follows directly from the name brainsprite.py.

**Comment by surchs** [comment]
the link you posted advocates for the kind of organization of this repo. I believe this is a relatively common way to [package repos](https://github.com/scikit-learn/scikit-learn/tree/master/sklearn). The name of the current core module (spritipy.py) is a bit meaningless though and could be changed to something more descriptive.

**Comment by pbellec** [comment]
alright so somewhere in that document they mention not having a subdirectory if you have a single file, which I think makes sense, as the purpose of a folder is to keep the clutter away, and has no point if there is no clutter to begin with.

**Comment by pbellec** [comment]
code is now at the base level.
